const config = {
  API_HOST: process.env.NEXT_PUBLIC_API_HOST,
  API_APPLY_TAB_AI: process.env.NEXT_PUBLIC_API_APPLY_TAB_AI,
  API_APPLY_TAB_AI_DEMO: process.env.NEXT_PUBLIC_API_APPLY_TAB_AI_DEMO,
  API_WOMPI_PUBLIC_KEY: process.env.NEXT_PUBLIC_API_WOMPI_PUBLIC_KEY,
  API_CHAT: process.env.NEXT_PUBLIC_CHAT_API_HOST,
  API_PURCHASE_ORDERS_AI: process.env.NEXT_PUBLIC_API_PURCHASE_ORDERS_AI
};

export default config;
